src/Entity/Entrada.php
<?php

namespace App\Entity;

use App\Entity\Traits\CssClass;
use App\Entity\Traits\LinksTrait;
use App\Entity\Traits\OfertTrait;
use App\Repository\EntradaRepository;
use App\Service\UploaderHelper;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\InverseJoinColumn;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\JoinTable;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EntradaRepository::class)]
class Entrada implements \Stringable
{
    use TimestampableEntity;

    use OfertTrait;

    use LinksTrait;

    use CssClass;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column]
    #[Groups('mail')]
    #[Assert\NotBlank]
    private string $titulo;

    #[ORM\Column(type: 'text', length: 8000, nullable: true)]
    #[Groups('mail')]
    private ?string $contenido = null;

    #[ORM\ManyToOne(inversedBy: 'entradas')]
    #[JoinColumn(nullable: false)]
    private ?User $autor = null;

    #[ORM\Column(nullable: true)]
    #[Groups('mail')]
    private ?string $imageFilename = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTimeInterface $publicadoAt = null;

    #[ORM\OneToMany(mappedBy: 'entrada', targetEntity: EntradaReference::class)]
    #[ORM\OrderBy(['posicion' => 'ASC'])]
    private ?Collection $entradaReferences;

    #[ORM\Column(type: 'integer')]
    private ?int $likes = 0;

    #[ORM\OneToMany(mappedBy: 'entrada', targetEntity: Comentario::class, fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private ?Collection $comentarios;

    #[ORM\ManyToMany(targetEntity: Principal::class, mappedBy: 'entradas')]
    private ?Collection $principals;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTimeInterface $eventoAt = null;

    #[ORM\Column(nullable: true)]
    private ?string $typeOrigin = null;

    #[ORM\Column(nullable: true)]
    private ?string $typeCarry = null;

    #[ORM\Column(nullable: true)]
    private ?int $orden = null;

    #[ORM\Column]
    private ?bool $encabezado = false;

    #[ORM\Column]
    private ?bool $destacado = false;

    #[ORM\ManyToOne(inversedBy: 'entradas')]
    private ?ModelTemplate $modelTemplate = null;

    #[ORM\ManyToMany(targetEntity: Contacto::class, inversedBy: 'entradas')]
    private ?Collection $contacto;

    #[ORM\Column]
    private ?bool $isSinTitulo = false;

    #[ORM\Column]
    private ?bool $isPermanente = false;

    #[ORM\Column(nullable: true)]
    private ?string $footer = null;

    #[ORM\ManyToMany(targetEntity: ButtonLink::class, inversedBy: 'entradas')]
    private ?Collection $button;

    #[ORM\Column(length: 150, unique: true, nullable: true)]
    private ?string $identificador = null;

    #[JoinTable(name: 'section_entrada')]
    #[JoinColumn(name: 'entrada_id', referencedColumnName: 'id')]
    #[InverseJoinColumn(name: 'section_id', referencedColumnName: 'id')]
    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'entradas')]
    private Collection $sections;

    public function __construct()
    {
        $this->entradaReferences = new ArrayCollection();
        $this->comentarios = new ArrayCollection();
        $this->principals = new ArrayCollection();
        $this->contacto = new ArrayCollection();
        $this->button = new ArrayCollection();
        $this->sections = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->titulo;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getContenido(): ?string
    {
        return $this->contenido;
    }

    public function setContenido(?string $contenido): self
    {
        $this->contenido = $contenido;

        return $this;
    }

    public function getAutor(): ?User
    {
        return $this->autor;
    }

    public function setAutor(?User $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getPublicadoAt(): ?DateTimeInterface
    {
        return $this->publicadoAt;
    }

    public function setPublicadoAt(?DateTimeInterface $publicadoAt): self
    {
        $this->publicadoAt = $publicadoAt;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return UploaderHelper::IMAGE_ENTRADA.'/'.$this->getImageFilename();
    }

    /**
     * @return Collection|null
     */
    public function getEntradaReferences(): ?Collection
    {
        return $this->entradaReferences;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(int $likes): self
    {
        $this->likes = $likes;

        return $this;
    }

    public function incrementaLikeCount(): self
    {
        $this->likes = $this->likes + 1;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getComentariosNoDeleted(): ?Collection
    {
        $criterio = EntradaRepository::createNoDeletedCriteria();

        return $this->comentarios->matching($criterio);
    }

    /**
     * @return Collection|null
     */
    public function getComentarios(): ?Collection
    {
        return $this->comentarios;
    }

    public function addComentario(Comentario $comentario): self
    {
        if (!$this->comentarios->contains($comentario)) {
            $this->comentarios[] = $comentario;
            $comentario->setEntrada($this);
        }

        return $this;
    }

    public function removeComentario(Comentario $comentario): self
    {
        if ($this->comentarios->contains($comentario)) {
            $this->comentarios->removeElement($comentario);
            // set the owning side to null (unless already changed)
            if ($comentario->getEntrada() === $this) {
                $comentario->setEntrada(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getPrincipals(): ?Collection
    {
        return $this->principals;
    }

    public function addPrincipal(Principal $principal): self
    {
        if (!$this->principals->contains($principal)) {
            $this->principals[] = $principal;
            $principal->addEntrada($this);
        }

        return $this;
    }

    public function removePrincipal(Principal $principal): self
    {
        if ($this->principals->contains($principal)) {
            $this->principals->removeElement($principal);
            $principal->removeEntrada($this);
        }

        return $this;
    }

    public function getEventoAt(): ?DateTimeInterface
    {
        return $this->eventoAt;
    }

    public function setEventoAt(?DateTimeInterface $eventoAt): self
    {
        $this->eventoAt = $eventoAt;

        return $this;
    }

    public function getTypeOrigin(): ?string
    {
        return $this->typeOrigin;
    }

    public function setTypeOrigin(?string $typeOrigin): self
    {
        $this->typeOrigin = $typeOrigin;

        return $this;
    }

    public function getTypeCarry(): ?string
    {
        return $this->typeCarry;
    }

    public function setTypeCarry(?string $typeCarry): self
    {
        $this->typeCarry = $typeCarry;

        return $this;
    }

    public function getOrden(): ?int
    {
        return $this->orden;
    }

    public function setOrden(?int $orden): self
    {
        $this->orden = $orden;

        return $this;
    }

    public function getEncabezado(): ?bool
    {
        return $this->encabezado;
    }

    public function setEncabezado(?bool $encabezado): self
    {
        $this->encabezado = $encabezado;

        return $this;
    }

    public function getDestacado(): ?bool
    {
        return $this->destacado;
    }

    public function setDestacado(?bool $destacado): self
    {
        $this->destacado = $destacado;

        return $this;
    }

    public function getModelTemplate(): ?ModelTemplate
    {
        return $this->modelTemplate;
    }

    public function setModelTemplate(?ModelTemplate $modelTemplate): self
    {
        $this->modelTemplate = $modelTemplate;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getContacto(): ?Collection
    {
        return $this->contacto;
    }

    public function addContacto(Contacto $contacto): self
    {
        if (!$this->contacto->contains($contacto)) {
            $this->contacto[] = $contacto;
        }

        return $this;
    }

    public function removeContacto(Contacto $contacto): self
    {
        $this->contacto->removeElement($contacto);

        return $this;
    }

    public function getIsSinTitulo(): ?bool
    {
        return $this->isSinTitulo;
    }

    public function setIsSinTitulo(?bool $isSinTitulo): self
    {
        $this->isSinTitulo = $isSinTitulo;

        return $this;
    }

    public function getIsPermanente(): ?bool
    {
        return $this->isPermanente;
    }

    public function setIsPermanente(?bool $isPermanente): self
    {
        $this->isPermanente = $isPermanente;

        return $this;
    }

    public function getFooter(): ?string
    {
        return $this->footer;
    }

src/Entity/ItemMenu.php
<?php

namespace App\Entity;

use App\Entity\Traits\CssClass;
use App\Entity\Traits\IdentificadorTrait;
use App\Repository\ItemMenuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Ramsey\Uuid\Doctrine\UuidGenerator;

#[\AllowDynamicProperties] #[ORM\Entity(repositoryClass: ItemMenuRepository::class)]
class ItemMenu implements \Stringable
{
    use TimestampableEntity;

    use CssClass;

    use IdentificadorTrait;

    #[ORM\Id]
    #[ORM\Column(length: 36)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private ?string $id = null;

    #[ORM\ManyToMany(targetEntity: Roles::class, inversedBy: 'itemMenus')]
    private ArrayCollection $role;

    #[ORM\Column]
    private ?string $label = null;

    #[ORM\Column(nullable: true)]
    private ?string $badge = null;

    #[ORM\Column(nullable: true)]
    private ?string $icon = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isExterno = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isActivo = null;

    #[ORM\ManyToOne(inversedBy: 'itemMenus')]
    private ?ItemMenu $parent = null;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: ItemMenu::class)]
    private Collection $itemMenus;

    #[ORM\ManyToOne(inversedBy: 'itemMenus')]
    private ?Principal $pathInterno = null;

    #[ORM\Column(nullable: true)]
    private ?string $pathLibre = null;

    #[ORM\ManyToMany(targetEntity: Menu::class, inversedBy: 'itemMenus')]
    private Collection $menu;

    public function __construct()
    {
        $this->role = new ArrayCollection();
        $this->itemMenus = new ArrayCollection();
        $this->menu = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->label;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getRole(): Collection
    {
        return $this->role;
    }

    public function addRole(Roles $role): self
    {
        if (!$this->role->contains($role)) {
            $this->role[] = $role;
        }

        return $this;
    }

    public function removeRole(Roles $role): self
    {
        $this->role->removeElement($role);

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getBadge(): ?string
    {
        return $this->badge;
    }

    public function setBadge(?string $badge): self
    {
        $this->badge = $badge;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    public function getIsExterno(): ?bool
    {
        return $this->isExterno;
    }

    public function setIsExterno(?bool $isExterno): self
    {
        $this->isExterno = $isExterno;

        return $this;
    }

    public function getIsActivo(): ?bool
    {
        return $this->isActivo;
    }

    public function setIsActivo(?bool $isActivo): self
    {
        $this->isActivo = $isActivo;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    public function getItemMenus(): Collection
    {
        return $this->itemMenus;
    }

    public function addItemMenu(self $itemMenu): self
    {
        if (!$this->itemMenus->contains($itemMenu)) {
            $this->itemMenus[] = $itemMenu;
            $itemMenu->setParent($this);
        }

        return $this;
    }

    public function removeItemMenu(self $itemMenu): self
    {
        if ($this->itemMenus->removeElement($itemMenu)) {
            // set the owning side to null (unless already changed)
            if ($itemMenu->getParent() === $this) {
                $itemMenu->setParent(null);
            }
        }

        return $this;
    }

    public function getPathInterno(): ?Principal
    {
        return $this->pathInterno;
    }

    public function getLinkRoute(): ?string
    {
        return $this->pathInterno->getLinkRoute();
    }

    public function setPathInterno(?Principal $pathInterno): self
    {
        $this->pathInterno = $pathInterno;

        return $this;
    }

    public function getPathLibre(): ?string
    {
        return $this->pathLibre;
    }

    public function setPathLibre(?string $pathLibre): self
    {
        $this->pathLibre = $pathLibre;

        return $this;
    }

    public function getMenu(): Collection
    {
        return $this->menu;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menu->contains($menu)) {
            $this->menu[] = $menu;
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        $this->menu->removeElement($menu);

        return $this;
    }

    public function getOrderitem(): ?int
    {
        return $this->orderitem;
    }

    public function setOrderitem(?int $orderitem): self
    {
        $this->orderitem = $orderitem;

        return $this;
    }

    public function getRol(): array
    {
        return $this->rol;
    }

    public function addRol(Roles $rol): self
    {
        if (!$this->rol->contains($rol)) {
            $this->rol[] = $rol;
        }

        return $this;
    }

    public function removeRol(Roles $rol): self
    {
        $this->rol->removeElement($rol);

        return $this;
    }
}

templates/principal/_form.html.twig
{{ form_start(form) }}
<div class="col-sm-11 mx-auto">
    <div class="row">
        {# {{ form_widget(form) }} #}
        <div class="col-sm-7">
            {{ form_row(form.titulo) }}
        </div>
        <div class="col-sm-5">
            <div class="row">
                <div class="col-sm-12">
                    {{ form_row(form.imageFile, {
                        attr: {
                            'placeholder': 'Seleccione una imagen para la página'
                        }
                    }) }}
                </div>
                <div class="col-sm-12">
                    {% if form.vars.data.imageFilename | default %}
                        <a href="{{ uploaded_asset(form.vars.data.imagePath) }}" target="_blank">
                            <img src="{{ form.vars.data.imagePath|imagine_filter('squared_thumbnail_small') }}"
                                 alt="Imagen">
                        </a>

                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            {{ form_row(form.contenido) }}
        </div>
        <div class="col-sm-4">
            {{ form_row(form.linkRoute) }}
        </div>
        <div class="col-sm-4 mx-auto">
            {{ form_row(form.linkPosting) }}
        </div>
        <div class="col-sm-2 text-center form-check text-dark mx-auto">
            <label for="entrada_isLinkExterno">
                Es Externo?<br/>
                {{ form_row(form.isLinkExterno) }}
            </label>
        </div>
        <div class="col-sm-4">
            {{ form_row(form.cssClass) }}
        </div><div class="col-sm-4">
            {{ form_row(form.isActive) }}
        </div>
        <div class="col-sm-6">
            {{ form_label(form.principal) }}
            {{ form_widget(form.principal) }}
            {{ form_help(form.principal) }}
        </div>
        <div class="col-sm-6">
            {{ form_label(form.modelTemplate) }}
            {{ form_widget(form.modelTemplate) }}
            {{ form_help(form.modelTemplate) }}
        </div>
    </div>
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
    <a href="{{ path('principal_index') }}">Volver al listado</a>
</div>

{{ form_end(form) }}

templates/principal/new.html.twig
{% extends 'base_admin_board.html.twig' %}

{% block title %}Crear Página Principal{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('select2-parent') }}
    <style>
        .custom-file-input ~ .custom-file-label.custom-file-label::after {
            content: "Elegir imagen";
            color: #fff;
            background-color: #9c27b0;
            top: 10px;
            box-shadow: 0 2px 2px 0 rgba(156, 39, 176, 0.14), 0 3px 1px -2px rgba(156, 39, 176, 0.2), 0 1px 5px 0 rgba(156, 39, 176, 0.12);
            position: absolute;
            /*padding: 3px 9px;*/
            /*margin: auto 1px;*/
            font-size: .75rem;
            font-weight: 400;
            /*line-height: 1.428571;*/
            text-decoration: none;
            text-transform: uppercase;
            letter-spacing: 0;
            cursor: pointer;
            border: 0 currentcolor;
            border-radius: 0.2rem;
            outline: 0;
            transition: box-shadow 0.2s cubic-bezier(0.4, 0, 1, 1), background-color 0.2s cubic-bezier(0.4, 0, 0.2, 1);
            will-change: box-shadow, transform;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title col-sm-6">Crear nueva página principal</h4>
                <a href="{{ path('principal_index') }}" class="pull-right text-dark col-sm-6">Volver al listado</a>
            </div>
            <div class="card-body">
                {{ include('principal/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}
{% block jslocal %}
    {{ encore_entry_script_tags('select2-parent') }}

{% endblock %}

templates/principal/show.html.twig
{% extends 'base_admin_board.html.twig' %}

{% block title %}Principal Datos{% endblock %}

{% block stylesheets %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('fonts/awesome/web-fonts-with-css/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('bt5-softui-dash/css/soft-ui-dashboard.min.css') }}">
    {{ encore_entry_link_tags('section_select') }}
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">Principal <i>{{ principal.linkRoute }}</i> <small>{{ principal.isActive ? '<i class="fa fa-check text-success"> </i> Activa' : '<i class="fa fa-times text-danger"> </i> Activa'  }}</small></h4>
                <p class="card-category"> Datos </p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Id</th>
                            <th>Titulo</th>
                            <th>linkRoute</th>
                        </tr>
                        <tr>
                            <td>{{ principal.id }}</td>
                            <td>{{ principal.titulo | raw }}</td>
                            <td>
                                <a href="{{ path('principal_ver', {'linkRoute': principal.linkRoute}) }}"
                                   target="_blank">
                                    <i class="fa fa-external-link-alt"> </i>
                                    {{ principal.linkRoute }}
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td colspan="2">{{ principal.contenido | raw}}</td>
                        </tr>
                        <tr>
                            <th>Imagen</th>
                            <th>Css</th>
                            <th>Autor</th>
                        </tr>
                        <tr>
                            <td>
                                {% if (principal.imageFilename != null) %}
                                    <img class="article-img" alt="{{ base.lema }}"
                                         src="{{ principal.imagePath|imagine_filter('squared_thumbnail_100') }}">
                                    <br/>
                                    {{ principal.imageFilename }}
                                {% else %}
                                    No tiene imagen
                                {% endif %}
                            </td>
                            <td>{{ principal.cssClass }}</td>
                            <td>{{ principal.autor }}</td>

                        </tr>
                        <tr>
                            <th>Creada</th>
                            <th>Actualizada</th>
                            <th>ModelTemplate</th>
                        </tr>
                        <tr>
                            <td>{{ principal.createdAt ? principal.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ principal.updatedAt ? principal.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ principal.modelTemplate}}</td>
                        </tr>
                        {% if brotes %}
                            <tr>
                                <th colspan="3" class="text-center">
                                    <h3>Páginas asociadas</h3>
                                </th>

                            </tr>
                            <tr>
                                <td>Título</td>
                                <td>LinkRoute</td>
                                <td><i class="fa fa-cogs"> </i> </td>
                            </tr>
                            {% for brote in brotes %}
                                <tr>
                                    <td>{{ brote.titulo }}</td>
                                    <td>
                                        {{ brote.linkRoute }}
                                        <a href="{{ path('principal_ver', {'linkRoute': brote.linkRoute}) }}"
                                           target="_blank"
                                        >
                                            <i class="fa fa-link"> </i><small> ver en pantalla nueva</small>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('principal_show', {'id': brote.id}) }}">
                                            <i class="fa fa-eye"> </i> <small> Ver datos</small>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}

                        {% endif %}
                        </tbody>
                    </table>


                    {% if principal.section %}
                        <tr>
                            <td colspan="10">
                                <div class="col-sm-12">
                                    <h3 class="text-center">Secciones asociadas</h3>
                                    <div style="font-size: 0.9rem"
                                         class="list-group small js-section-list col-sm-12"
                                         data-url="{{ path('admin_principal_list_section', {id: principal.id}) }}"
                                         data-principal="{{ principal.id }}"
                                    >
                                    </div>
                                    <div class="col-sm-12 text-center">
                                        <a href="{{ path('principal_agregar_seccion', { 'id': principal.id }) }}"
                                           class="btn btn-link btn-sm btn-modal">
                                            <i class="fa fa-plus"> Sección</i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                </div>

                <a href="{{ path('admin') }}" class="btn btn-info">Volver al listado</a>

                <a href="{{ path('principal_edit', {'id': principal.id}) }}" class="btn btn-warning">Editar</a>

                {{ include('principal/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
    {% include('admin/_modal.html.twig') %}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bt5-softui-dash/js/core/popper.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bt5-softui-dash/js/core/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bt5-softui-dash/js/soft-ui-dashboard.js') }}"
    {{ encore_entry_script_tags('section_select') }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"
            integrity="sha512-ELgdXEUQM5x+vB2mycmnSCsiDZWQYXKwlzh9+p+Hff4f5LA+uf0w2pOp3j7UAuSAajxfEzmYZNOOLQuiotrt9Q=="
            crossorigin="anonymous"></script>

    <script src="{{ asset('js/admin_section_principal_form.js') }}"></script>

    <script type="application/javascript">
        $(function () {
            $(".btn-modal").click(function (ev) {
                ev.preventDefault();
                const target = $(this).attr("href");
                $("#modalPlantillaWeb .modal-content").load(target, function () {
                    $("#modalPlantillaWeb").modal("show");
                });
            });
        });


    </script>
{% endblock %}
{% block jslocal %}
    {{ parent() }}
    <script>
        $('#admin').addClass('active');
    </script>
{% endblock %}

templates/principal/vistaAgregaSection.html.twig
{%  if principal is defined %}
{{ form_start(form, {'action' : path('principal_agregar_seccion', { 'id': principal.id })}) }}
    {% else %}
        {{ form_start(form) }}
{% endif %}

<div class="modal-header panel-info">
    <h5 class="modal-title" id="exampleModalLabel">Agregar Sección </h5>
</div>
<div id="reserva" class="modal-body">
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title "> Secciones </h4>
        </div>
        <div class="card-body">

            <div class="col-sm-12 p-0">
                <label for="{{ form.section.vars.id}}" class="label text-dark">
                    <i class="fa fa-list"> </i> Sección
                </label>
                {{ form_widget(form.section) }}
            </div>

            <div class="col-sm-12 p-0 text-center">
                {{ form_row(form.save) }}
            </div>
            {{ form_widget(form._token) }}
        </div>
    </div>
    <a class="btn-outline-primary" href="{{ path('admin_section_new') }}">
        Crear Sección
    </a>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>
{{ form_end(form, {'render_rest': false}) }}